export const menuItems = [
  // ==================== KAFFEE ====================
  {
    itemId: 1,
    category: "Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Kombi Americano",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 90 },
      { size: "Hippie", price: 80 },
      { size: "Bulli", price: 90 },
    ],
    quantity: 0,
  },
  {
    itemId: 2,
    category: "Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Kombi Latte",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 110 },
      { size: "Hippie", price: 100 },
      { size: "Bulli", price: 110 },
    ],
    quantity: 0,
  },
  {
    itemId: 3,
    category: "Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Kombi Flat White",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 120 },
      { size: "Hippie", price: 100 },
      { size: "Bulli", price: 120 },
    ],
    quantity: 0,
  },
  {
    itemId: 4,
    category: "Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Kombi Cappuccino",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 130 },
      { size: "Hippie", price: 120 },
      { size: "Bulli", price: 130 },
    ],
    quantity: 0,
  },
  {
    itemId: 5,
    category: "Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Kombi Macchiato",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 130 },
      { size: "Hippie", price: 130 },
      { size: "Bulli", price: 140 },
    ],
    quantity: 0,
  },

  // ==================== KLASSIK KAFFEE ====================
  {
    itemId: 6,
    category: "Klassik Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Spanish Latte",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 120 },
      { size: "Hippie", price: 110 },
      { size: "Bulli", price: 120 },
    ],
    quantity: 0,
  },
  {
    itemId: 7,
    category: "Klassik Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Vanilla Latte",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 120 },
      { size: "Hippie", price: 110 },
      { size: "Bulli", price: 120 },
    ],
    quantity: 0,
  },
  {
    itemId: 8,
    category: "Klassik Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Hazelnut Latte",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 120 },
      { size: "Hippie", price: 110 },
      { size: "Bulli", price: 120 },
    ],
    quantity: 0,
  },
  {
    itemId: 9,
    category: "Klassik Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Caramel Latte",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 120 },
      { size: "Hippie", price: 110 },
      { size: "Bulli", price: 120 },
    ],
    quantity: 0,
  },

  // ==================== SPECIALTY KAFFEE ====================
  {
    itemId: 10,
    category: "Specialty Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Salted Caramel",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 120 },
      { size: "Hippie", price: 110 },
      { size: "Bulli", price: 120 },
    ],
    quantity: 0,
  },
  {
    itemId: 11,
    category: "Specialty Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Hazelnut Mocha",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 120 },
      { size: "Hippie", price: 110 },
      { size: "Bulli", price: 120 },
    ],
    quantity: 0,
  },
  {
    itemId: 12,
    category: "Specialty Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Pistachio Latte",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 120 },
      { size: "Hippie", price: 110 },
      { size: "Bulli", price: 120 },
    ],
    quantity: 0,
  },
  {
    itemId: 13,
    category: "Specialty Kaffee",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Roasted Almond",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 120 },
      { size: "Hippie", price: 110 },
      { size: "Bulli", price: 120 },
    ],
    quantity: 0,
  },

  // ==================== KAFFEE FRAPPE ====================
  {
    itemId: 14,
    category: "Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Dark Mocha (Java Chips)",
    ingredients: [],
    sizes: [
      { size: "Bulli", price: 160 },
    ],
    quantity: 0,
  },
  {
    itemId: 15,
    category: "Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Hazelnut",
    ingredients: [],
    sizes: [
      { size: "Bulli", price: 160 },
    ],
    quantity: 0,
  },
  {
    itemId: 16,
    category: "Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Hazelnut Mocha",
    ingredients: [],
    sizes: [
      { size: "Bulli", price: 160 },
    ],
    quantity: 0,
  },
  {
    itemId: 17,
    category: "Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Salted Caramel",
    ingredients: [],
    sizes: [
      { size: "Bulli", price: 160 },
    ],
    quantity: 0,
  },
  {
    itemId: 18,
    category: "Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Oreo Coffee",
    ingredients: [],
    sizes: [
      { size: "Bulli", price: 160 },
    ],
    quantity: 0,
  },
  {
    itemId: 19,
    category: "Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Dirty Matcha",
    ingredients: [],
    sizes: [
      { size: "Bulli", price: 160 },
    ],
    quantity: 0,
  },
  {
    itemId: 20,
    category: "Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Kombiccino",
    ingredients: [],
    sizes: [
      { size: "Bulli", price: 170 },
    ],
    quantity: 0,
  },

  // ==================== NON-KAFFEE LATTE ====================
  {
    itemId: 21,
    category: "Non-Kaffee Latte",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Black Tea",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },
  {
    itemId: 22,
    category: "Non-Kaffee Latte",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Black Tea Latte",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },
  {
    itemId: 23,
    category: "Non-Kaffee Latte",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Matcha Latte",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },
  {
    itemId: 24,
    category: "Non-Kaffee Latte",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Babyccino",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },
  {
    itemId: 25,
    category: "Non-Kaffee Latte",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Dark Babyccino",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },

  // ==================== FRUITEE LATTE ====================
  {
    itemId: 26,
    category: "Fruitee Latte",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Strawberry Latte",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },
  {
    itemId: 27,
    category: "Fruitee Latte",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Blueberry Latte",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },
  {
    itemId: 28,
    category: "Fruitee Latte",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Mango Latte",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },
  {
    itemId: 29,
    category: "Fruitee Latte",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Mixed Berries",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },

  // ==================== THE BEETLES JUICE ====================
  {
    itemId: 30,
    category: "The Beetles Juice",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "John Lemon Ginger",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },
  {
    itemId: 31,
    category: "The Beetles Juice",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Paul Strawberry",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },
  {
    itemId: 32,
    category: "The Beetles Juice",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Ringo Mango",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },
  {
    itemId: 33,
    category: "The Beetles Juice",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "George Blueberry",
    ingredients: [],
    sizes: [
      { size: "Kafer", price: 0 },
      { size: "Hippie", price: 0 },
      { size: "Bulli", price: 0 },
    ],
    quantity: 0,
  },

  // ==================== NON-KAFFEE FRAPPE ====================
  {
    itemId: 34,
    category: "Non-Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Strawberry",
    ingredients: [],
    sizes: [{ size: "Bulli", price: 0 }],
    quantity: 0,
  },
  {
    itemId: 35,
    category: "Non-Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Blueberry",
    ingredients: [],
    sizes: [{ size: "Bulli", price: 0 }],
    quantity: 0,
  },
  {
    itemId: 36,
    category: "Non-Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Mango",
    ingredients: [],
    sizes: [{ size: "Bulli", price: 0 }],
    quantity: 0,
  },
  {
    itemId: 37,
    category: "Non-Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Mixed Berries",
    ingredients: [],
    sizes: [{ size: "Bulli", price: 0 }],
    quantity: 0,
  },
  {
    itemId: 38,
    category: "Non-Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Oreo",
    ingredients: [],
    sizes: [{ size: "Bulli", price: 0 }],
    quantity: 0,
  },
  {
    itemId: 39,
    category: "Non-Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Matcha",
    ingredients: [],
    sizes: [{ size: "Bulli", price: 0 }],
    quantity: 0,
  },
  {
    itemId: 40,
    category: "Non-Kaffee Frappe",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Java Chips",
    ingredients: [],
    sizes: [{ size: "Bulli", price: 0 }],
    quantity: 0,
  },

  // ==================== SNACKS ====================
  {
    itemId: 41,
    category: "Snacks",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Pizza 2Pi Burger",
    ingredients: [],
    sizes: [{ size: "Regular", price: 190 }],
    quantity: 0,
  },
  {
    itemId: 42,
    category: "Snacks",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Pizza Pi Burger",
    ingredients: [],
    sizes: [{ size: "Regular", price: 100 }],
    quantity: 0,
  },
  {
    itemId: 43,
    category: "Snacks",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Double Grilled Cheese",
    ingredients: [],
    sizes: [{ size: "Regular", price: 90 }],
    quantity: 0,
  },
  {
    itemId: 44,
    category: "Snacks",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Cheese Burger",
    ingredients: [],
    sizes: [{ size: "Regular", price: 90 }],
    quantity: 0,
  },
  {
    itemId: 45,
    category: "Snacks",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Regular Burger",
    ingredients: [],
    sizes: [{ size: "Regular", price: 80 }],
    quantity: 0,
  },
  {
    itemId: 46,
    category: "Snacks",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Hotdog Sandwich",
    ingredients: [],
    sizes: [{ size: "Regular", price: 80 }],
    quantity: 0,
  },
  {
    itemId: 47,
    category: "Snacks",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "Cheese Sticks",
    ingredients: [],
    sizes: [{ size: "Regular", price: 60 }],
    quantity: 0,
  },
  {
    itemId: 48,
    category: "Snacks",
    itemImg: "/drinks/no-drink-image.svg",
    itemName: "French Fries",
    ingredients: [],
    sizes: [{ size: "Regular", price: 60 }],
    quantity: 0,
  },
];